# Generated by Django 5.2 on 2025-05-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_image', models.ImageField(upload_to='found_items/')),
                ('predicted_category', models.CharField(choices=[('stationery', 'Stationery'), ('notebooks', 'Notebooks / Textbooks'), ('bags', 'Bags / Backpacks'), ('clothing', 'Clothing (Jackets, Hoodies, Uniforms)'), ('footwear', 'Footwear'), ('water_bottle', 'Water Bottles'), ('lunch_box', 'Lunch Boxes'), ('eyeglasses', 'Eyeglasses'), ('electronics', 'Electronics'), ('sports_equipment', 'Sports Equipment'), ('art_supplies', 'Art Supplies'), ('accessories', 'Accessories (Watches, Jewelry)'), ('id_cards', 'ID Cards / Bus Passes')], max_length=50)),
                ('item_name', models.CharField(blank=True, max_length=100)),
                ('location_found', models.CharField(max_length=200)),
                ('date_found', models.DateField()),
                ('time_found', models.TimeField()),
                ('description', models.TextField(blank=True)),
                ('finder_name', models.CharField(max_length=100)),
                ('finder_email', models.EmailField(max_length=254)),
                ('finder_phone', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('returned', 'Returned')], default='pending', max_length=20)),
                ('ml_confidence', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('date_lost', models.DateField()),
                ('time_lost', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='lost_items/')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
    ]
