# Generated by Django 5.2 on 2025-05-05 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='founditem',
            old_name='location_found',
            new_name='location',
        ),
    ]
