# Generated by Django 5.2 on 2025-05-05 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_rename_location_found_founditem_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='founditem',
            old_name='item_image',
            new_name='image',
        ),
    ]
