# Generated by Django 5.2 on 2025-05-05 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_rename_item_image_founditem_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='founditem',
            old_name='predicted_category',
            new_name='category',
        ),
    ]
