# Generated by Django 4.2.21 on 2025-05-11 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0004_rename_predicted_category_founditem_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('matched_by', models.CharField(blank=True, max_length=100)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('found_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_found_items', to='home_page.founditem')),
                ('lost_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_lost_items', to='home_page.lostitem')),
            ],
        ),
    ]
