# Generated by Django 4.2.21 on 2025-05-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0005_matcheditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditem',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
