# Generated by Django 4.2.21 on 2025-05-11 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0006_alter_founditem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founditem',
            name='ml_confidence',
        ),
    ]
